#!/usr/bin/env bash
# Deploy FinTrack infrastructure to Azure
# Prerequisites: Azure CLI (az login), jq

set -euo pipefail

RESOURCE_GROUP="rg-fintrack"
LOCATION="westeurope"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

command -v az  >/dev/null 2>&1 || { echo "ERROR: Azure CLI not found"; exit 1; }
command -v jq  >/dev/null 2>&1 || { echo "ERROR: jq not found (brew install jq / apt install jq)"; exit 1; }

echo "[1/4] Creating resource group..."
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none

echo "[2/4] Deploying infrastructure..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --query "properties.outputs" \
  --output json)

SQL_SERVER=$(echo "$DEPLOYMENT_OUTPUT"  | jq -r '.sqlServerFqdn.value')
DB_NAME=$(echo "$DEPLOYMENT_OUTPUT"     | jq -r '.sqlDatabaseName.value')
STORAGE_NAME=$(echo "$DEPLOYMENT_OUTPUT"| jq -r '.storageAccountName.value')
STORAGE_KEY=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.storageAccountKey.value')

echo "[3/4] Writing app/config.py..."
cat > "$SCRIPT_DIR/../app/config.py" <<EOF
# config.py — Generated by infra/deploy.sh

DB_SERVER   = "${SQL_SERVER}"
DB_NAME     = "${DB_NAME}"
DB_USER     = "sqladmin"
DB_PASSWORD = "Password123!"

STORAGE_CONNECTION_STRING = (
    "DefaultEndpointsProtocol=https;"
    "AccountName=${STORAGE_NAME};"
    "AccountKey=${STORAGE_KEY};"
    "EndpointSuffix=core.windows.net"
)

LOG_LEVEL = "DEBUG"
EOF

echo "[4/4] Uploading sample blobs..."
echo "CustomerName,Balance,TransactionDate
Alice Johnson,5234.50,2024-01-15
Bob Martinez,12890.00,2024-01-16" | az storage blob upload \
  --account-name "$STORAGE_NAME" \
  --account-key "$STORAGE_KEY" \
  --container-name "finance-reports" \
  --name "monthly-summary-2024-01.csv" \
  --type block \
  --overwrite \
  --data @- \
  --output none 2>/dev/null

echo '{"export":"finance-db","format":"bacpac","date":"2024-01-10"}' | az storage blob upload \
  --account-name "$STORAGE_NAME" \
  --account-key "$STORAGE_KEY" \
  --container-name "db-backups" \
  --name "finance-db-2024-01-10.bacpac" \
  --type block \
  --overwrite \
  --data @- \
  --output none 2>/dev/null

echo ""
echo "=== Done ==="
echo "  SQL Server : $SQL_SERVER"
echo "  Database   : $DB_NAME"
echo "  Storage    : $STORAGE_NAME"
echo ""
echo "Next: initialise the database"
echo "  sqlcmd -S $SQL_SERVER -d $DB_NAME -U sqladmin -P 'Password123!' -i database/schema.sql"
echo "  sqlcmd -S $SQL_SERVER -d $DB_NAME -U sqladmin -P 'Password123!' -i database/seed.sql"
